sudo: false
language: python

python:
  - "2.7"

env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py27-django111

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
