language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.9.6
install:
  - pip install -r requirements.txt
  - pip install Django==$DJANGO_VERSION
branches:
  only:
    - master
script:
  - python example/manage.py test
